# LIBRERIAS

In [3]:
import pandas as pd # pip installa pandas

# cargar datos

In [13]:
df =pd.read_csv("./dataset.csv")
df.head(5)

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
4,183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129

In [10]:
df.loc[0:2]

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129

In [11]:
df.loc[[1,7],["favorites"]]

   favorites
1      500.0
7        NaN

In [12]:
df.loc[:,["favorites"]]

    favorites
0        23.0
1       500.0
2       190.0
3       131.0
4       113.0
5       492.0
6       158.0
7         NaN
8       198.0
9       272.0
10       43.0
11      349.0
12      467.0
13       50.0
14      418.0
15      361.0
16      346.0
17      296.0
18      315.0
19      133.0
20       92.0
21      255.0
22      432.0
23      430.0
24      424.0
25      488.0
26      318.0

In [16]:
df.loc[1:9,["favorites"]]

   favorites
1      500.0
2      190.0
3      131.0
4      113.0
5      492.0
6      158.0
7        NaN
8      198.0
9      272.0

In [17]:
df.head(5)

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
4,183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129

In [19]:
#seleccionar por condicion
df[df["favorites"]>400]

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
12,183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
14,183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721
22,183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
23,183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
24,183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
25,183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721

In [20]:
df[(df["favorites"]>400) & (df["mentions"]>20)]

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
23,183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
24,183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
25,183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721

In [ ]:
#df.loc [9,19]
#df[df["favorites"]]
#df[df.loc[9:19],df["favorites"]>400]

In [8]:
df.describe()

,id,favorites,retweets,mentions,followers,followees
count,27.000000,26.000000,26.000000,26.000000,26.000000,27.000000
mean,183734.000000,280.538462,80.000000,15.423077,352.807692,1190.185185
std,7.937254,153.377242,40.303846,9.596554,375.319493,1965.735995
min,183721.000000,23.000000,21.000000,1.000000,12.000000,129.000000
25%,183727.500000,139.250000,45.500000,8.250000,21.000000,258.000000
50%,183734.000000,305.500000,79.000000,16.000000,332.000000,351.000000
75%,183740.500000,422.500000,110.750000,23.500000,389.000000,1822.000000
max,183747.000000,500.000000,146.000000,29.000000,982.000000,9918.000000